// ============================================================
// PART 1 — Imports & Types
// ============================================================

import type {
  StoryConfig,
  Character,
  SceneDirectionData,
  WriterProfile,
  EpisodeManuscript,
  TranslatedManuscriptEntry,
} from '@/lib/studio-types';
import {
  episodeToMarkdown,
  markdownToEpisode,
  episodeFilePath,
  translatedManuscriptToMarkdown,
  markdownToTranslatedManuscript,
} from '@/lib/markdown-serializer';
import { logger } from '@/lib/logger';

/** A single file entry destined for a GitHub repo. */
export interface RepoFile {
  path: string;
  content: string;
}

// ============================================================
// PART 2 — YAML Helpers (JSON-based, human-readable)
// ============================================================

/**
 * Serialize a value to a YAML-like string.
 * Uses JSON with 2-space indent for simplicity and git-diff friendliness.
 * Prefixes with a `# Auto-generated` comment for clarity.
 */
function toYaml(value: unknown, comment?: string): string {
  const header = comment ? `# ${comment}\n` : '# Auto-generated by NOA Studio\n';
  return header + JSON.stringify(value, null, 2) + '\n';
}

/**
 * Parse a YAML-like string back to an object.
 * Strips leading comment lines (starting with #) then parses as JSON.
 */
function fromYaml<T>(raw: string): T | null {
  if (!raw || typeof raw !== 'string') return null;
  try {
    // Strip comment lines at the top
    const lines = raw.split('\n');
    const jsonLines = lines.filter(line => !line.trimStart().startsWith('#'));
    const cleaned = jsonLines.join('\n').trim();
    if (!cleaned) return null;
    return JSON.parse(cleaned) as T;
  } catch (err) {
    logger.warn('project-serializer', 'fromYaml JSON parse failed', err);
    return null;
  }
}

// ============================================================
// PART 3 — Character Serialization
// ============================================================

/**
 * Serialize a Character to a YAML-compatible string.
 */
export function characterToYaml(char: Character): string {
  if (!char) return '';
  return toYaml(char, `Character: ${char.name ?? 'Unknown'}`);
}

/**
 * Parse a YAML string back to a Character.
 */
export function yamlToCharacter(yaml: string): Character {
  const parsed = fromYaml<Character>(yaml);
  if (!parsed) {
    return { id: '', name: 'Unknown', role: '', traits: '', appearance: '', dna: 0 };
  }
  return {
    ...parsed,
    id: parsed.id ?? '',
    name: parsed.name ?? 'Unknown',
    role: parsed.role ?? '',
    traits: parsed.traits ?? '',
    appearance: parsed.appearance ?? '',
    dna: parsed.dna ?? 0,
  };
}

// ============================================================
// PART 4 — Config -> Repo Files (Serialize)
// ============================================================

/**
 * Serialize a StoryConfig into a list of files for a GitHub repo.
 *
 * Output structure:
 * - novel.yaml              (core config)
 * - characters/{name}.yaml  (one per character)
 * - world/setting.yaml      (world 3-tier data)
 * - direction/scene-direction.yaml (SceneDirectionData)
 * - .noa/profile.json       (WriterProfile if available)
 * - volumes/vol-XX/ep-XXX.md (one per episode manuscript)
 */
export function configToRepoFiles(
  config: StoryConfig,
  writerProfile?: WriterProfile,
): RepoFile[] {
  if (!config) return [];

  const files: RepoFile[] = [];

  // --- novel.yaml: core config (exclude large nested objects) ---
  const core: Record<string, unknown> = {
    genre: config.genre,
    title: config.title ?? '',
    totalEpisodes: config.totalEpisodes ?? 25,
    episode: config.episode ?? 1,
    synopsis: config.synopsis ?? '',
    povCharacter: config.povCharacter ?? '',
    setting: config.setting ?? '',
    primaryEmotion: config.primaryEmotion ?? '',
    platform: config.platform ?? 'MOBILE',
    narrativeIntensity: config.narrativeIntensity ?? 'standard',
    guardrails: config.guardrails,
    subGenres: config.subGenres ?? [],
    prismMode: config.prismMode ?? 'OFF',
  };
  files.push({ path: 'novel.yaml', content: toYaml(core, 'NOA Novel — Core Config') });

  // --- characters/{safeName}.yaml ---
  const characters = config.characters ?? [];
  for (const char of characters) {
    if (!char) continue;
    const safeName = sanitizeFilename(char.name || char.id || 'unnamed');
    files.push({
      path: `characters/${safeName}.yaml`,
      content: characterToYaml(char),
    });
  }

  // --- world/setting.yaml: world 3-tier data ---
  const worldData: Record<string, unknown> = {};
  const worldKeys = [
    'corePremise', 'powerStructure', 'currentConflict',
    'worldHistory', 'socialSystem', 'economy', 'magicTechSystem',
    'factionRelations', 'survivalEnvironment',
    'culture', 'religion', 'education', 'lawOrder', 'taboo',
    'dailyLife', 'travelComm', 'truthVsBeliefs',
  ] as const;
  let hasWorldData = false;
  for (const key of worldKeys) {
    const val = config[key];
    if (val !== undefined && val !== null && val !== '') {
      worldData[key] = val;
      hasWorldData = true;
    }
  }
  if (hasWorldData) {
    files.push({
      path: 'world/setting.yaml',
      content: toYaml(worldData, 'World Setting — 3-Tier Framework'),
    });
  }

  // --- direction/scene-direction.yaml ---
  if (config.sceneDirection && Object.keys(config.sceneDirection).length > 0) {
    files.push({
      path: 'direction/scene-direction.yaml',
      content: toYaml(config.sceneDirection, 'Scene Direction Data'),
    });
  }

  // --- .noa/profile.json (WriterProfile — 작가 학습 프로필, 다른 기기 sync용) ---
  // useProjectManager.syncProjectToGithub에서 loadProfile() 결과를 전달하면
  // GitHub 레포에 커밋되어 다른 기기/세션에서도 프로필 이어받기 가능.
  if (writerProfile && writerProfile.episodeCount > 0) {
    files.push({
      path: '.noa/profile.json',
      content: writerProfileToJson(writerProfile),
    });
  }

  // --- volumes/vol-XX/ep-XXX.md ---
  const manuscripts = config.manuscripts ?? [];
  for (const ms of manuscripts) {
    if (!ms) continue;
    const vol = ms.volume ?? 1;
    const path = ms.filePath ?? episodeFilePath(ms.episode, vol);
    files.push({
      path,
      content: episodeToMarkdown(ms, vol),
    });
  }

  // --- translations/<lang>/volumes/vol-XX/ep-XXX.md ---
  // 번역본을 원본과 병렬로 관리. lang 코드는 소문자화(en/jp/cn).
  const translations = config.translatedManuscripts ?? [];
  for (const t of translations) {
    if (!t) continue;
    const vol = 1; // TranslatedManuscriptEntry에는 volume 정보가 없음 — 원본 매칭 시 vol=1 가정
    const path = episodeFilePath(t.episode, vol, t.targetLang);
    files.push({
      path,
      content: translatedManuscriptToMarkdown(t),
    });
  }

  return files;
}

// ============================================================
// PART 5 — Repo Files -> Config (Deserialize)
// ============================================================

/**
 * Deserialize repo files back into a partial StoryConfig.
 * Handles missing files gracefully — only populates fields for files found.
 */
export function repoFilesToConfig(files: RepoFile[]): Partial<StoryConfig> {
  if (!files || files.length === 0) return {};

  const result: Partial<StoryConfig> = {};

  // Index files by path for fast lookup
  const fileMap = new Map<string, string>();
  for (const f of files) {
    if (f?.path && f.content != null) {
      fileMap.set(f.path, f.content);
    }
  }

  // --- novel.yaml ---
  const novelRaw = fileMap.get('novel.yaml');
  if (novelRaw) {
    const core = fromYaml<Record<string, unknown>>(novelRaw);
    if (core) {
      if (core.genre !== undefined) result.genre = core.genre as StoryConfig['genre'];
      if (core.title !== undefined) result.title = String(core.title);
      if (typeof core.totalEpisodes === 'number') result.totalEpisodes = core.totalEpisodes;
      if (typeof core.episode === 'number') result.episode = core.episode;
      if (core.synopsis !== undefined) result.synopsis = String(core.synopsis);
      if (core.povCharacter !== undefined) result.povCharacter = String(core.povCharacter);
      if (core.setting !== undefined) result.setting = String(core.setting);
      if (core.primaryEmotion !== undefined) result.primaryEmotion = String(core.primaryEmotion);
      if (core.platform !== undefined) result.platform = core.platform as StoryConfig['platform'];
      if (core.narrativeIntensity !== undefined) result.narrativeIntensity = core.narrativeIntensity as StoryConfig['narrativeIntensity'];
      if (core.guardrails !== undefined) result.guardrails = core.guardrails as StoryConfig['guardrails'];
      if (Array.isArray(core.subGenres)) result.subGenres = core.subGenres as string[];
      if (core.prismMode !== undefined) result.prismMode = core.prismMode as StoryConfig['prismMode'];
    }
  }

  // --- characters/*.yaml ---
  const characters: Character[] = [];
  for (const [path, content] of fileMap) {
    if (path.startsWith('characters/') && path.endsWith('.yaml')) {
      const char = yamlToCharacter(content);
      if (char.name) characters.push(char);
    }
  }
  if (characters.length > 0) result.characters = characters;

  // --- world/setting.yaml ---
  const worldRaw = fileMap.get('world/setting.yaml');
  if (worldRaw) {
    const world = fromYaml<Record<string, string>>(worldRaw);
    if (world) {
      const worldKeys = [
        'corePremise', 'powerStructure', 'currentConflict',
        'worldHistory', 'socialSystem', 'economy', 'magicTechSystem',
        'factionRelations', 'survivalEnvironment',
        'culture', 'religion', 'education', 'lawOrder', 'taboo',
        'dailyLife', 'travelComm', 'truthVsBeliefs',
      ] as const;
      for (const key of worldKeys) {
        if (world[key] !== undefined) {
          (result as Record<string, unknown>)[key] = world[key];
        }
      }
    }
  }

  // --- direction/scene-direction.yaml ---
  const directionRaw = fileMap.get('direction/scene-direction.yaml');
  if (directionRaw) {
    const direction = fromYaml<SceneDirectionData>(directionRaw);
    if (direction) result.sceneDirection = direction;
  }

  // --- volumes/vol-XX/ep-XXX.md (원본) ---
  const manuscripts: EpisodeManuscript[] = [];
  for (const [path, content] of fileMap) {
    if (path.startsWith('volumes/') && path.endsWith('.md')) {
      const ms = markdownToEpisode(content, path);
      manuscripts.push(ms);
    }
  }
  if (manuscripts.length > 0) {
    manuscripts.sort((a, b) => a.episode - b.episode);
    result.manuscripts = manuscripts;
  }

  // --- translations/<lang>/volumes/vol-XX/ep-XXX.md (번역본) ---
  const translations: TranslatedManuscriptEntry[] = [];
  for (const [path, content] of fileMap) {
    if (path.startsWith('translations/') && path.endsWith('.md')) {
      const t = markdownToTranslatedManuscript(content, path);
      if (t) translations.push(t);
    }
  }
  if (translations.length > 0) {
    translations.sort((a, b) =>
      a.targetLang === b.targetLang ? a.episode - b.episode : a.targetLang.localeCompare(b.targetLang)
    );
    result.translatedManuscripts = translations;
  }

  return result;
}

/**
 * Repo 파일에서 .noa/profile.json 을 추출해 WriterProfile 로 복원.
 * GitHub pull 후 StudioShell 등에서 호출 → saveProfile(profile)로 localStorage 반영.
 * 파일 없으면 null.
 */
export function extractWriterProfile(files: RepoFile[]): WriterProfile | null {
  if (!files || files.length === 0) return null;
  const file = files.find((f) => f?.path === '.noa/profile.json');
  if (!file || typeof file.content !== 'string') return null;
  return jsonToWriterProfile(file.content);
}

// ============================================================
// PART 6 — Writer Profile Helpers
// ============================================================

/**
 * Serialize a WriterProfile to a JSON string for the .noa/profile.json file.
 */
export function writerProfileToJson(profile: WriterProfile): string {
  return JSON.stringify(profile, null, 2) + '\n';
}

/**
 * Parse a JSON string back to a WriterProfile.
 */
export function jsonToWriterProfile(json: string): WriterProfile | null {
  try {
    return JSON.parse(json) as WriterProfile;
  } catch (err) {
    logger.warn('project-serializer', 'jsonToWriterProfile parse failed', err);
    return null;
  }
}

// ============================================================
// PART 7 — Utilities
// ============================================================

/**
 * Sanitize a string for use as a filename.
 * Replaces unsafe characters and trims whitespace.
 */
function sanitizeFilename(name: string): string {
  return (name || 'unnamed')
    .replace(/[/\\?%*:|"<>]/g, '-')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 100)
    || 'unnamed';
}
