// ============================================================
// PART 1 — Module Header
// ============================================================
//
// docx-export.ts — 번역 결과 DOCX 내보내기 (편집사·출판사 제출용).
//
// 시장 분석 4차 §4 §6 핵심 요구:
//   "EPUB / DOCX / 플랫폼 제출 포맷"
//   "출판사·편집자 협업 자료"
//
// docx 라이브러리에 의존하지 않고 결정론적 DOCX (Open XML) 생성.
// 단순 패러그래프·제목·헤더만 — 복잡한 스타일은 후속 사이클.
//
// Faithful + Market dual track 지원.
// 한 호출에 둘 다 또는 하나만 export 가능.
//
// [C] zip 의존 없음 — 텍스트 위주 (다운로드 어댑터는 호출자에서 JSZip 사용)
// [G] 정적 XML 조립 — 빠름
// [K] 단일 책임 — DOCX 문자열 생성만
// ============================================================

// ============================================================
// PART 2 — Types
// ============================================================

export interface DocxChapterInput {
  title: string;
  /** Faithful 본문 (옵션) */
  contentFaithful?: string;
  /** Market 본문 (옵션) */
  contentMarket?: string;
  /** legacy 단일 본문 (옵션) */
  content?: string;
}

export interface DocxBuildOptions {
  /** 표지 제목 */
  title: string;
  /** 저자 */
  author?: string;
  /** 번역가 */
  translator?: string;
  /** track 선택 */
  track: 'faithful' | 'market' | 'both';
  /** 언어 코드 (ko/en/ja/zh) */
  lang: string;
}

export interface DocxBundle {
  /** word/document.xml 본문 */
  documentXml: string;
  /** [Content_Types].xml */
  contentTypesXml: string;
  /** _rels/.rels */
  relsXml: string;
  /** word/_rels/document.xml.rels */
  documentRelsXml: string;
  /** word/styles.xml */
  stylesXml: string;
  /** docProps/core.xml */
  coreXml: string;
  /** docProps/app.xml */
  appXml: string;
}

// ============================================================
// PART 3 — XML escape
// ============================================================

function escapeXml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

// ============================================================
// PART 4 — Paragraph builders
// ============================================================

function pStyle(text: string, style: 'Heading1' | 'Heading2' | 'Normal' | 'Subtitle' = 'Normal'): string {
  const safe = escapeXml(text);
  return `<w:p><w:pPr><w:pStyle w:val="${style}"/></w:pPr><w:r><w:t xml:space="preserve">${safe}</w:t></w:r></w:p>`;
}

function pBlank(): string {
  return `<w:p/>`;
}

function pBreak(): string {
  return `<w:p><w:r><w:br w:type="page"/></w:r></w:p>`;
}

function bodyParagraphs(text: string): string {
  return text
    .split(/\n\s*\n/)
    .map((p) => p.trim())
    .filter((p) => p.length > 0)
    .map((p) => pStyle(p, 'Normal'))
    .join('');
}

// ============================================================
// PART 5 — DOCX 본문 조립
// ============================================================

export function buildDocxBundle(
  chapters: DocxChapterInput[],
  options: DocxBuildOptions,
): DocxBundle {
  const { title, author, translator, track, lang } = options;
  const safeTitle = escapeXml(title);
  const safeAuthor = escapeXml(author ?? '');
  const safeTranslator = escapeXml(translator ?? '');
  const safeLang = escapeXml(lang);

  // 본문 paragraphs
  const sections: string[] = [];

  // 표지
  sections.push(pStyle(title, 'Heading1'));
  if (author) sections.push(pStyle(`Author: ${author}`, 'Subtitle'));
  if (translator) sections.push(pStyle(`Translator: ${translator}`, 'Subtitle'));
  sections.push(pStyle('Generated by Loreguard Fiction-native Translation Studio', 'Subtitle'));
  sections.push(pBlank());

  if (track === 'both') {
    // Market 본문 메인
    sections.push(pStyle('Market-ready Localization (출판본)', 'Heading1'));
    sections.push(pBlank());
    for (const ch of chapters) {
      sections.push(pStyle(ch.title, 'Heading2'));
      const txt = ch.contentMarket ?? ch.content ?? '';
      sections.push(bodyParagraphs(txt));
      sections.push(pBreak());
    }
    // Faithful 부록
    sections.push(pStyle('Source-faithful Translation (저작권 archive 부록)', 'Heading1'));
    sections.push(pBlank());
    for (const ch of chapters) {
      sections.push(pStyle(ch.title, 'Heading2'));
      const txt = ch.contentFaithful ?? ch.content ?? '';
      sections.push(bodyParagraphs(txt));
      sections.push(pBreak());
    }
  } else {
    // 단일 track
    for (const ch of chapters) {
      sections.push(pStyle(ch.title, 'Heading2'));
      const txt =
        track === 'faithful'
          ? ch.contentFaithful ?? ch.content ?? ''
          : ch.contentMarket ?? ch.content ?? '';
      sections.push(bodyParagraphs(txt));
      sections.push(pBreak());
    }
  }

  const body = sections.join('');

  const documentXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
<w:body>
${body}
<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr>
</w:body>
</w:document>`;

  const stylesXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:style w:type="paragraph" w:default="1" w:styleId="Normal">
    <w:name w:val="Normal"/>
    <w:rPr><w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/><w:sz w:val="22"/></w:rPr>
  </w:style>
  <w:style w:type="paragraph" w:styleId="Heading1">
    <w:name w:val="Heading 1"/>
    <w:basedOn w:val="Normal"/>
    <w:next w:val="Normal"/>
    <w:rPr><w:b/><w:sz w:val="36"/></w:rPr>
  </w:style>
  <w:style w:type="paragraph" w:styleId="Heading2">
    <w:name w:val="Heading 2"/>
    <w:basedOn w:val="Normal"/>
    <w:next w:val="Normal"/>
    <w:rPr><w:b/><w:sz w:val="28"/></w:rPr>
  </w:style>
  <w:style w:type="paragraph" w:styleId="Subtitle">
    <w:name w:val="Subtitle"/>
    <w:basedOn w:val="Normal"/>
    <w:rPr><w:i/><w:sz w:val="22"/></w:rPr>
  </w:style>
</w:styles>`;

  const relsXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/>
  <Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/>
</Relationships>`;

  const documentRelsXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>
</Relationships>`;

  const contentTypesXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
  <Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>
  <Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>
  <Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>
</Types>`;

  const coreXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/">
  <dc:title>${safeTitle}</dc:title>
  <dc:creator>${safeAuthor}</dc:creator>
  <dc:contributor>${safeTranslator}</dc:contributor>
  <dc:language>${safeLang}</dc:language>
  <cp:lastModifiedBy>Loreguard Translation Studio</cp:lastModifiedBy>
</cp:coreProperties>`;

  const appXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties">
  <Application>Loreguard Translation Studio (Fiction-native, Cross-border)</Application>
  <DocSecurity>0</DocSecurity>
</Properties>`;

  return {
    documentXml,
    stylesXml,
    relsXml,
    documentRelsXml,
    contentTypesXml,
    coreXml,
    appXml,
  };
}

// ============================================================
// PART 6 — JSZip 어댑터 (호출자 측)
// ============================================================

/**
 * DOCX bundle → JSZip 친화 file map.
 * 호출자가 JSZip 인스턴스 만들고 이 map 으로 file 추가 후 .blob() / .download() 처리.
 *
 * 사용 예 (호출자):
 *   const bundle = buildDocxBundle(...);
 *   const files = docxBundleToFiles(bundle);
 *   const zip = new JSZip();
 *   Object.entries(files).forEach(([path, content]) => zip.file(path, content));
 *   const blob = await zip.generateAsync({ type: 'blob' });
 */
export function docxBundleToFiles(bundle: DocxBundle): Record<string, string> {
  return {
    '[Content_Types].xml': bundle.contentTypesXml,
    '_rels/.rels': bundle.relsXml,
    'word/document.xml': bundle.documentXml,
    'word/_rels/document.xml.rels': bundle.documentRelsXml,
    'word/styles.xml': bundle.stylesXml,
    'docProps/core.xml': bundle.coreXml,
    'docProps/app.xml': bundle.appXml,
  };
}
